[package]
name = "kata"
version = "0.5.0"
description = "A desktop frontend for a user-configured KataGo engine"
authors = ["Kata contributors"]
edition = "2021"

[lib]
name = "kata_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
rfd = "0.15"
